import paramiko

def read_secrets():
    secrets = {}
    with open("secrets.env", "r") as f:
        for line in f:
            if "=" in line:
                k, v = line.strip().split("=", 1)
                secrets[k] = v
    return secrets

def debug_ps():
    creds = read_secrets()
    ip = creds.get("speedy_mini_ip")
    user = creds.get("speedy_mini_username")
    password = creds.get("speedy_mini_password")

    print(f"Connecting to {user}@{ip}...")
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
    try:
        client.connect(ip, username=user, password=password, timeout=10)
        
        print("--- Podman PS (All) ---")
        stdin, stdout, stderr = client.exec_command("podman ps -a")
        print(stdout.read().decode('utf-8', errors='replace'))
        
        print("--- Agent Logs (Full) ---")
        # Try finding container ID from ps? No, name is reliable if generated by compose
        stdin, stdout, stderr = client.exec_command("podman logs master_of_puppets_agent_1")
        print(stdout.read().decode('utf-8', errors='replace'))
        print(stderr.read().decode('utf-8', errors='replace'))
        
        print("--- Inspect Agent ---")
        stdin, stdout, stderr = client.exec_command("podman inspect master_of_puppets_agent_1 --format '{{.State.Status}} {{.State.ExitCode}} {{.State.Error}}'")
        print(stdout.read().decode('utf-8', errors='replace'))
        
    except Exception as e:
        print(f"[ERR] Debug Failed: {e}")
    finally:
        client.close()

if __name__ == "__main__":
    debug_ps()
