
version: '3.8'
services:
  puppet:
    image: localhost/master-of-puppets-node:latest
    container_name: puppet-node
    network_mode: host
    environment:
      - AGENT_URL=https://localhost:8001
      - JOIN_TOKEN=eyJ0IjogIjRjYWUwYzViNjM5NzQ2OTE4ZDBlODUyZmUxYTBkMzU3IiwgImNhIjogIi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQnp6Q0NBWFdnQXdJQkFnSVFmdFpKaGU2ZFJlUDk2NkhjMGRaUnFqQUtCZ2dxaGtqT1BRUURBakJHTVIwd1xuR3dZRFZRUUtFeFJOWVhOMFpYSWdiMllnVUhWd2NHVjBjeUJEUVRFbE1DTUdBMVVFQXhNY1RXRnpkR1Z5SUc5bVxuSUZCMWNIQmxkSE1nUTBFZ1VtOXZkQ0JEUVRBZUZ3MHlOakF4TVRZeE1UUXlNekZhRncwek5qQXhNVFF4TVRReVxuTXpGYU1FWXhIVEFiQmdOVkJBb1RGRTFoYzNSbGNpQnZaaUJRZFhCd1pYUnpJRU5CTVNVd0l3WURWUVFERXh4TlxuWVhOMFpYSWdiMllnVUhWd2NHVjBjeUJEUVNCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRFxuQVFjRFFnQUVoamd0T21mRjhZeE40czlPN2VqVmZKRm9VUVpZcTZuK21Qc0pRNHNZNEo5ZFdDcFRLS2twYURTVlxuM3daTGpnc2w0RFFnYlpTYm9STExxY1M3Tld1YkpLTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZFxuRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTVlxMU5nNGU1T21lbnozd0tsWjl6Mk94Ynh5TUFvR1xuQ0NxR1NNNDlCQU1DQTBnQU1FVUNJRkMzYjEzYzRqT3ZrMDVlclpncmNsVzVKVnZHQWZ6L0xUdHNtbEEzT1FEUlxuQWlFQTM2ZmZyR2ZKUTBjbnU4QUJZMEp1eTBFM0xneHZwTGpLeUNOZDN3YTFuUDQ9XG4tLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tXG4ifQ==
      - MOUNT_DATA=
      - NODE_TAGS=general,linux,arm64
    volumes:
      - ./secrets:/app/secrets
    restart: unless-stopped
