networks:
  puppeteer_default:
    external: true
services:
  node:
    build:
      context: .
      dockerfile: Containerfile.node
    environment:
    - NODE_TAGS=general,linux,test-group
    - JOB_IMAGE=docker.io/library/python:3.12-alpine
    - AGENT_URL=https://puppeteer-agent-1:8001
    - JOIN_TOKEN=eyJ0IjogImE0YmY1MWI5OTAxZjQ1MmZiMTU0OTc0NWE4ZWU5NGIwIiwgImNhIjogIi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJRkZ6Q0NBditnQXdJQkFnSVVQNHZXSS8xREtGMzdSYWJHUHpxU1NLY3ZhZjB3RFFZSktvWklodmNOQVFFTFxuQlFBd096RWlNQ0FHQTFVRUF3d1pUV0Z6ZEdWeUlHOW1JRkIxY0hCbGRITWdVbTl2ZENCRFFURVZNQk1HQTFVRVxuQ2d3TVFtRnRZbWxpWVc1dVpYSnpNQjRYRFRJMk1ESXlOekUxTVRVME1Gb1hEVE0yTURJeU5URTFNVFUwTUZvd1xuT3pFaU1DQUdBMVVFQXd3WlRXRnpkR1Z5SUc5bUlGQjFjSEJsZEhNZ1VtOXZkQ0JEUVRFVk1CTUdBMVVFQ2d3TVxuUW1GdFltbGlZVzV1WlhKek1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBbytmZlxubExqbG9Zc2ZpRGkyQ0pBSjNnczgxWTgxQ0hNOE5KakdBRzdoUWpnMDZzN1RqZnBMMmNwRjh2SGtadUg0OWhYbFxuMzBVYWpBdHpDcVo4TjIxS0I3UlRsY3B0WXp2WVNVYWxCNkxnQzBaSjN3R1R0MWdLMzRrWkcyMnB6Ry9KYzZWRFxuN1FQTHNjanJBQVZjQ1UwK3haT3dzdGdMOW4yN3llMXY3TTNaY1Y0cS91MVZxMXNtTngwMXQ1cktVMXdnU1pMMVxuQm8xVTZtQXRrcC9QUUluYnQ4NzNpYS9zT1gvbnEveDUreDdtRTkrUnFaa3ZPYW9iMXhVVXhyNWRJTmJSWmN0a1xuUFRjMVpVcG5Sc0NveXRxdGhBU0o0WnJKRHF2Tm14SklLZVZuTytwcHoxZ3lwaGdOcE40Q0ZiNXp5OUtKcFNGMlxuczZNenQ5KzUwOWY5bkE2UHBzRjhuRkxHK05XRnNDNnpiZlZYajd0ak9NemNhR0k4M1pSM0FGdFhGUWo1MkpJT1xualV0Y2xxQmFrRzkyWEJKQnV0bmswM2xueHo4MWtqTUlrZHQyZ1hHQ2xTL0RKQnZVa0Z1ODliM0pTVWdxOFZZOVxub3VqUkVtQmRmL2lGazFSTUlXY1RlNjZBc2tuQThnWkF2OU5rTGFKbzJLS2k4U3pNeHBJYTRMTTFBMmFHbURMTlxucDZOK0t5OHVOZ1VIdUF3dForOC9IYmc3OCtTVGJGZTl1OGZNOWhOR0U4ZWNlekJUc0RvQW5ETytIQ1F5Y2Vhb1xuSFlBR1ZxY1ZTdkNEemtDMzdFL3hjdWluUFFUZSt3dDEwZy9zeXVGbmtRQUovSE5Bbnhxd0FTeDAxVE5IeG5aNVxuSERoN3A0Y0d1QXdUdUNQTWxEMnIrYnM2LzJjZU9oejdGYkIxS05FQ0F3RUFBYU1UTUJFd0R3WURWUjBUQVFIL1xuQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBbUVKYXVOLzE4TFk1ZFY3bm9NUlpabzg0V3BpQlxueGxoSUtMc1hyYUVMUURqdGtKVFhGVzBPaEJzWjRQd0RVZ2IxdEs0WWF6WFdYWmtDS05QbVR2OUtvSVFWc1ZSL1xuTUtjUi9ORE9DTGlKZFM5ckVwMEdtNFdSYzJPRG5wVWdDcU1PMVY4ZHF5cFlQdmpYRHlZNzUvTFFGRjg4eG1hTlxuMXl1Z1gxcG9yc0pUakNzNVZLeXA3anoxV2xYeUJuYmdrMFRCS2RHcEsrU0ZtbWswR3I0L2c0OVFQOUo4Z0RZU1xueitEY2ZKeWYrQmt6aTdwL290Tlhjay9TcTliTG5zTWFsZ2VWL25veVNiazhuWlQxSE1KRmFQZXBoZXJ4K0wrVVxuVk1heTBZbytkZnZ5d2FaNWQ4andOV1dyeWRhVFpRT1JUK2pVa0hOVWFJVENNalF0YXI4T1FvQks2MStVQ0NXZlxuOWpndG1LLzY5YXA5WGxkY1RIdVlWa0N3WFRCaXUwOEVuamVVTEtKZlJYeU5SWjRraVU1UFN6Rm5HdWF3WXI2NFxuUnI2SURaMUVYMGpkRFdXZzl4emV4TWJjMjVyUjFuS05uL0NiUithVlNUekR6Mi9mM21IRHJMVldiZm9NRXAvT1xuUytqNW1SUFAyTVJXNHpHYVNoOWQvczQvdFEreFo3TUJjOU0zUSthcWNXYnhEc25qazYvQlJYZkdhcWJCWWxtYVxuVUl5Z08wWEtiQ1hLZGJhVjFPUk5qSWxuNm5KZ0QwVmN1WExpZlRzS3A2RGlWOTgzVkdwY0svN1BaSkZUaFArRFxucGsvYlZtZFNENHNObUhOTUxsclBQeGN4UFB4dGt5K3ZGY0hpL2J1bHVpd0NCcmsrUEJ6Vk5TUHk5dFhRellEaFxuZEtjOWFqR3o3T25OcHRFPVxuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLVxuIn0=
    - ROOT_CA_PATH=/app/secrets/root_ca.crt
    - PYTHONUNBUFFERED=1
    image: localhost/master-of-puppets-node:latest
    networks:
    - puppeteer_default
    privileged: true
    restart: always
    volumes:
    - ./secrets:/app/secrets
  sidecar:
    image: localhost/mop-sidecar-proxy:v1
    network_mode: service:node
    restart: always
version: '3'
